default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: futaboo_development

test:
  <<: *default
  database: futaboo_test
  
production:
  <<: *default
  database: futaboo_production
  username: futaboo
  password: <%= ENV["FUTABOO_DATABASE_PASSWORD"] %>
